theme: jekyll-theme-cayman

title: Zilong Li
author: Zilong Li
description: Computational fluid dynamics, machine learning, reduced order modeling, and building better models :)

url: "https://lzlcfd.github.io/"

header_pages:
  - index.md
  - research.md
  - publications.md
  - code.md
  - teaching.md
  - contact.md

social-network-links:
  email: zilongli@iastate.edu
  github: zilongli

markdown: kramdown
